# Generated by Django 2.1 on 2020-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apply_info',
            fields=[
                ('apply_info_no', models.IntegerField(primary_key=True, serialize=False)),
                ('apply_info_name', models.CharField(max_length=30)),
                ('apply_info_address', models.CharField(max_length=30)),
                ('apply_info_phone', models.CharField(max_length=30)),
                ('apply_info_waste_type_no', models.IntegerField()),
                ('apply_info_fee', models.CharField(max_length=30)),
                ('apply_info_code', models.CharField(max_length=30)),
                ('apply_info_user_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('area_no', models.IntegerField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=30)),
                ('area_name2', models.CharField(max_length=30)),
                ('area_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='board',
            fields=[
                ('board_no', models.IntegerField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=30)),
                ('board_ctnt', models.CharField(max_length=30)),
                ('board_reg_user_no', models.IntegerField()),
                ('board_reg_date', models.CharField(max_length=30)),
                ('board_waste_area_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='board_review',
            fields=[
                ('board_review_no', models.IntegerField(primary_key=True, serialize=False)),
                ('board_revie_board_no', models.IntegerField()),
                ('board_review_ctnt', models.CharField(max_length=30)),
                ('board_review_reg_user_no', models.IntegerField()),
                ('board_review_reg_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_info_no', models.IntegerField(primary_key=True, serialize=False)),
                ('user_info_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='waste_div',
            fields=[
                ('waste_div_no', models.IntegerField(primary_key=True, serialize=False)),
                ('waste_div_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='waste_type',
            fields=[
                ('waste_type_no', models.IntegerField(primary_key=True, serialize=False)),
                ('waste_type_waste_div_no', models.IntegerField()),
                ('waste_type_name', models.CharField(max_length=30)),
                ('waste_type_kor_name', models.CharField(max_length=30)),
                ('waste_type_size', models.CharField(max_length=30)),
                ('waste_type_fee', models.CharField(max_length=30)),
                ('waste_type_area_no', models.IntegerField()),
            ],
        ),
    ]
