# Generated by Django 2.1 on 2020-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_auto_20200423_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_info_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
