# Generated by Django 2.1 on 2020-05-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_user_info_user_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='forpay',
            fields=[
                ('random_no', models.IntegerField(primary_key=True, serialize=False)),
                ('tid', models.CharField(max_length=30)),
            ],
        ),
    ]
