# Generated by Django 2.1 on 2020-05-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_forpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forpay',
            name='random_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
