# Generated by Django 2.1 on 2020-05-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_auto_20200521_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_image_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
