# Generated by Django 2.1 on 2020-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0007_apply_info_apply_info_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_info',
            name='apply_info_user_no',
            field=models.CharField(max_length=30),
        ),
    ]
